# Generated by Django 3.1.6 on 2021-02-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='color',
            field=models.CharField(choices=[('A', 'Animal'), ('B', 'Black'), ('Bl', 'Blue'), ('Cl', 'Clear'), ('G', 'Green'), ('Go', 'Gold'), ('Gr', 'Grey'), ('Mu', 'Multi'), ('Ne', 'Neon'), ('O', 'Orange'), ('P', 'Purple'), ('Ra', 'Rainbow'), ('R', 'Red'), ('Si', 'Silver'), ('T', 'Teal'), ('Y', 'Yellow')], default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='shoe',
            name='size',
            field=models.CharField(choices=[('4', '4'), ('4.5', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10'), ('10.5', '10.5'), ('11', '11')], default='4', max_length=4),
        ),
        migrations.AddField(
            model_name='shoe',
            name='style',
            field=models.CharField(choices=[('An', 'Ankle-High/Booties'), ('Fl', 'Flats'), ('HH', 'High Heels'), ('Kn', 'Knee-High Boots'), ('Ru', 'Running Shoes'), ('Sa', 'Sandals'), ('Th', 'Thigh-High Boots'), ('We', 'Wedges/Platforms')], default='An', max_length=2),
        ),
    ]
