# Generated by Django 3.1.6 on 2021-02-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210217_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='designer',
            field=models.BooleanField(null=True, verbose_name='Designer:'),
        ),
    ]
