# Generated by Django 3.1.6 on 2021-02-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_shoe_designer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='designer',
            field=models.BooleanField(default=False, verbose_name='Designer:'),
        ),
    ]
