# Generated by Django 3.1.6 on 2021-02-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210218_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
