# Generated by Django 3.1.6 on 2021-02-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_shoe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='name',
            field=models.CharField(default='Please enter name of shoe', max_length=250),
        ),
    ]
