# Generated by Django 3.1.7 on 2021-02-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210219_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='name',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo',
        ),
    ]
