# Generated by Django 3.1.7 on 2021-02-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_replica'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='replicas',
            field=models.ManyToManyField(to='main_app.Replica'),
        ),
    ]
